-- WezTerm config (Windows)
-- This is WezTerm's only config file; changes apply automatically on save, no restart needed.
-- Anything not set here uses WezTerm's defaults.
-- Docs: https://wezterm.org/config/lua/config/index.html

local wezterm = require 'wezterm'

-- config_builder: misspelled or unknown options raise an error instead of being silently ignored.
local config = wezterm.config_builder()

-- ========== Appearance ==========

-- Font: JetBrains Mono ships with WezTerm; Microsoft YaHei for CJK text
-- (without it, CJK falls back to a Japanese font).
config.font = wezterm.font_with_fallback { 'JetBrains Mono', 'Microsoft YaHei' }
config.font_size = 14

-- Colors: follow Windows light/dark mode.
-- To change theme: Ctrl+Shift+P, search "color scheme" to preview, or see https://wezterm.org/colorschemes/
local function is_dark()
  return wezterm.gui == nil or wezterm.gui.get_appearance():find 'Dark' ~= nil
end
config.color_scheme = is_dark() and 'Catppuccin Mocha' or 'Catppuccin Latte'

-- Disable cursor blinking. WezTerm's own default cursor style (SteadyBlock) never blinks anyway;
-- this only matters for programs that explicitly request a blinking cursor style (e.g. Claude
-- Code's input prompt) — without it, WezTerm resets the blink phase on every repaint, and heavy
-- repainting (streaming output) makes a blinking cursor look like it's flickering rapidly.
config.cursor_blink_rate = 0

-- Window: tabs live in the title bar, keeping Windows-style minimize/maximize/close buttons.
config.window_decorations = 'INTEGRATED_BUTTONS|RESIZE'
config.initial_cols = 120
config.initial_rows = 32
config.window_padding = { left = 8, right = 8, top = 6, bottom = 4 }

-- GPU rendering (for machines with a discrete or integrated GPU; use 'Software' on machines without one).
config.front_end = 'WebGpu'

-- ========== Behavior ==========

config.default_prog = { 'powershell.exe', '-NoLogo' }  -- program a new tab opens by default
config.scrollback_lines = 20000                         -- lines you can scroll back through
config.audible_bell = 'Disabled'                        -- no beep
-- Passive endings (crash, dropped connection, non-zero exit) hold the tab open and explain why.
-- Active endings (you typed exit/quit and it exited cleanly) close the tab automatically, since
-- that was your own intent. Ctrl+Shift+W always force-closes a held tab either way.
config.exit_behavior = 'CloseOnCleanExit'
-- Terse ([Exited with code N]) rather than Verbose: Verbose prints the full launch command,
-- which for an SSH tab means dumping the entire multi-line reconnect script inline.
config.exit_behavior_messaging = 'Terse'

-- Normalize pasted newlines to CR (same as pressing Enter). Windows sends CRLF by default,
-- and remote vim etc. count CR and LF as separate line breaks, adding a blank line after every line.
config.canonicalize_pasted_newlines = 'CarriageReturn'

-- SSH always goes through Windows' built-in ssh (OpenSSH); ~/.ssh/config is the single host list.
-- Disable the SSH:/SSHMUX: entries auto-generated by WezTerm's built-in SSH (libssh-rs):
-- its password prompt enables bracketed paste and never disables it, so pasting into
-- old bash (e.g. CentOS 7) shows 0~...1~.
config.ssh_domains = {}

-- Since WezTerm's own SSH is unused (above), also stop it from pointing every local pane's
-- SSH_AUTH_SOCK at its own agent-forwarding proxy socket (nightly default as of 2024/2025).
-- That path isn't the real Windows OpenSSH agent pipe, so ssh can't find the agent through it
-- and falls back to reading private keys straight from disk, prompting for the passphrase on
-- every connection even though the real ssh-agent service already has the key unlocked.
config.mux_enable_ssh_agent = false

-- Launch menu: right-click the + on the tab bar (no default shortcut; or search "launcher" in Ctrl+Shift+P).
-- SSH entries are generated from ~/.ssh/config (to add a host, edit only the ssh config, not this file).
-- Closing it: Esc always works; right-clicking again on the blank area below the list also closes
-- it (confirmed by testing — the same button that opens it also closes it). Left-clicking outside
-- the list does NOT close it — there's no generic "click away to dismiss" handling for this widget.
config.launch_menu = {
  { label = 'PowerShell', args = { 'powershell.exe', '-NoLogo' } },
  { label = 'CMD', args = { 'cmd.exe' } },
  -- Admin entries elevate through Windows' built-in sudo (Settings > For developers > sudo,
  -- mode set to "Run in the same window as sudo" so the elevated process stays in this tab
  -- instead of popping a separate console); a UAC prompt appears.
  { label = 'PowerShell (Admin)', args = { 'sudo', '--inline', 'powershell.exe', '-NoLogo' } },
  { label = 'CMD (Admin)', args = { 'sudo', '--inline', 'cmd.exe' } },
}
local ssh_hosts = {}
for host in pairs(wezterm.enumerate_ssh_hosts()) do
  table.insert(ssh_hosts, host)
end
table.sort(ssh_hosts)
-- SSH tab behavior: ssh exiting cleanly (you typed exit/logout — an active, intentional end) closes
-- the tab automatically, per exit_behavior = CloseOnCleanExit. ssh exiting non-zero (dropped connection,
-- a passive/unwanted end) instead shows a one-line prompt: Enter reconnects, Ctrl+Shift+W closes the tab.
-- Note: use only single quotes in the script (Windows strips double quotes when passing command-line arguments).
-- Mouse-tracking reset: if a remote program (tmux/vim/htop/...) left SGR mouse reporting on when the
-- link dropped (a network blip kills the pty before it can send the disable sequence), WezTerm keeps
-- turning every mouse move in this pane into '<Cb;Cx;CyM' escape codes fed into the next shell, which
-- shows up as '35;33;16M: command not found' garbage. Disable all mouse modes before every (re)connect.
-- Tab marker (see format-tab-title below): the script tells WezTerm the target host and
-- disconnect state directly via OSC 1337 SetUserVar at the moment each happens, rather than
-- WezTerm guessing from process info or on-screen text (both go stale: once ssh exits, there's
-- no ssh process left to read the host from, and disconnect text printed to the screen never
-- leaves the scrollback on its own if the reconnected session stays quiet).
local reconnect = [[
function Set-WeztermVar($n, $v) {
  $b64 = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($v))
  Write-Host -NoNewline "$([char]27)]1337;SetUserVar=$n=$b64$([char]7)"
}
$mouseReset = "$([char]27)[?1000l$([char]27)[?1002l$([char]27)[?1003l$([char]27)[?1006l$([char]27)[?1015l"
Set-WeztermVar 'ssh_target' '%s'
while ($true) {
  Write-Host -NoNewline $mouseReset
  Set-WeztermVar 'ssh_disconnected' '0'
  ssh -o ConnectTimeout=10 %s
  if ($LASTEXITCODE -eq 0) { break }
  Set-WeztermVar 'ssh_disconnected' '1'
  Write-Host ''
  Write-Host '[disconnected] press Enter to reconnect to %s, or Ctrl+Shift+W to close this tab' -ForegroundColor Yellow
  [void](Read-Host)
  Start-Sleep -Milliseconds 300
}
]]
for _, host in ipairs(ssh_hosts) do
  table.insert(config.launch_menu, {
    label = 'SSH ' .. host,
    args = { 'powershell.exe', '-NoLogo', '-NoProfile', '-Command', reconnect:format(host, host, host) },
  })
end

-- ========== Mouse bindings ==========
-- Shift always bypasses whatever program has grabbed the mouse (vim's `mouse=a`, tmux's
-- `mouse on`, Claude CLI, any nesting of these) and forces WezTerm's own native handling —
-- this is decided locally before anything is sent over SSH, so it works the same no matter
-- how many layers (ssh > tmux > vim) are stacked underneath.
-- Copy: Shift+drag-release already defaults to copying the selection to the clipboard.
-- Paste: WezTerm has no default Right-button binding at all, so this is a pure addition.
config.mouse_bindings = {
  {
    event = { Down = { streak = 1, button = 'Right' } },
    mods = 'SHIFT',
    action = wezterm.action.PasteFrom 'Clipboard',
  },
}

-- ========== Key bindings ==========
-- Custom bindings (everything else is WezTerm's default), defined below:
--   Ctrl+Shift+T  duplicate tab,  Ctrl+Alt+M  merge into another tab as a split,
--   Ctrl+Alt+T  split out into a tab,  Ctrl+Alt+W  detach into a new window
-- Ctrl+Shift+P opens the command palette, which lists every action with its shortcut.
-- Admin PowerShell/CMD are launch-menu entries only (the + button on the tab bar), not a shortcut,
-- since elevation is rare enough that a dedicated hotkey isn't worth the accidental-elevation risk.

-- ========== Tab titles ==========
-- ssh tabs show the target you typed (e.g. myubuntu, 10.10.140.170); other tabs use the default title.
-- Through a jump host the foreground process is the "ssh -W ... jump" tunnel, so walk up to the ssh you typed.

local function user_ssh_argv(pane)
  local info = pane:get_foreground_process_info()
  for _ = 1, 4 do
    if not info then return nil end
    local name = (info.name or ''):lower()
    local argv = info.argv or {}
    if (name == 'ssh' or name == 'ssh.exe') and argv[2] ~= '-W' then return argv end
    info = info.ppid and wezterm.procinfo.get_info_for_pid(info.ppid)
  end
end

-- Target host = first non-option argument (options that take a value, like -p 22, skip their value too)
local function ssh_target(argv)
  local i = 2
  while argv[i] do
    local a = argv[i]
    if a:sub(1, 1) ~= '-' then return a end
    if #a == 2 and ('BbcDEeFIiJLlmOoPpQRSWw'):find(a:sub(2), 1, true) then i = i + 1 end
    i = i + 1
  end
end

-- ========== Ctrl+Shift+T: duplicate the current tab (like Tabby's Duplicate) ==========
-- Opens another tab identical to the current one:
--   running ssh (from the menu or typed by hand) -> new tab runs ssh with the same arguments (with Enter-to-reconnect)
--   anything else (PowerShell, CMD, ...)       -> new tab runs the same program in the same directory
-- ssh opens a new connection: key-based hosts log straight in, password hosts ask again.

-- The program the tab was started with = walk up until the parent is wezterm-gui
local function root_process(pane)
  local info = pane:get_foreground_process_info()
  for _ = 1, 10 do
    if not info or not info.ppid then return info end
    local parent = wezterm.procinfo.get_info_for_pid(info.ppid)
    if not parent or (parent.name or ''):lower():find('wezterm') then return info end
    info = parent
  end
  return info
end

local function ps_quote(s)
  if s:match('^[%w@%.%-_:/=,]+$') then return s end
  return "'" .. s:gsub("'", "''") .. "'"
end

config.keys = {
  {
    key = 'T', mods = 'CTRL|SHIFT',
    action = wezterm.action_callback(function(win, pane)
      local act = wezterm.action
      local ok, argv = pcall(user_ssh_argv, pane)
      if ok and argv then
        local parts = {}
        for i = 2, #argv do table.insert(parts, ps_quote(argv[i])) end
        local target_label = ssh_target(argv) or 'host'
        win:perform_action(act.SpawnCommandInNewTab {
          args = { 'powershell.exe', '-NoLogo', '-NoProfile', '-Command',
                   reconnect:format(target_label, table.concat(parts, ' '), target_label) },
        }, pane)
        return
      end
      local ok2, root = pcall(root_process, pane)
      if ok2 and root and root.argv and #root.argv > 0 then
        local fg = pane:get_foreground_process_info()
        win:perform_action(act.SpawnCommandInNewTab {
          args = root.argv,
          cwd = (fg and fg.cwd) or root.cwd,
        }, pane)
      else
        win:perform_action(act.SpawnTab 'CurrentPaneDomain', pane)
      end
    end),
  },
}

-- ========== Tab <-> split ==========
-- Ctrl+Alt+M: merge the current pane into another tab as a split. Two lists pop up: first pick the
--             target tab, then pick right/bottom/left/top. The character at the left of each row is
--             its shortcut, just press it; Esc cancels.
-- Ctrl+Alt+T: split the current pane out into its own new tab.
-- Ctrl+Alt+W: detach the current pane into a brand new OS window.
-- The pane is only moved; ssh sessions / programs inside keep running.

local function pane_label(p)
  local ok, argv = pcall(user_ssh_argv, p)
  return (ok and argv and ssh_target(argv)) or p:get_title()
end

local directions = {
  { id = '--right',  label = 'Right' },
  { id = '--bottom', label = 'Bottom' },
  { id = '--left',   label = 'Left' },
  { id = '--top',    label = 'Top' },
}

table.insert(config.keys, {
  key = 'm', mods = 'CTRL|ALT',
  action = wezterm.action_callback(function(win, pane)
    local cur = pane:tab():tab_id()
    local choices = {}
    for i, t in ipairs(win:mux_window():tabs()) do
      if t:tab_id() ~= cur then
        local target = t:active_pane()
        table.insert(choices, { id = tostring(target:pane_id()), label = 'Tab ' .. i .. '  ' .. pane_label(target) })
      end
    end
    if #choices == 0 then return end
    win:perform_action(wezterm.action.InputSelector {
      title = 'Merge into which tab',
      choices = choices,
      action = wezterm.action_callback(function(win2, pane2, target_id)
        if not target_id then return end
        win2:perform_action(wezterm.action.InputSelector {
          title = 'Place on which side',
          choices = directions,
          alphabet = '1234',
          action = wezterm.action_callback(function(_, _, dir)
            if not dir then return end
            wezterm.run_child_process {
              'wezterm', 'cli', 'split-pane', dir,
              '--pane-id', target_id, '--move-pane-id', tostring(pane:pane_id()),
            }
            pane:activate()
          end),
        }, pane2)
      end),
    }, pane)
  end),
})

table.insert(config.keys, {
  key = 't', mods = 'CTRL|ALT',
  action = wezterm.action_callback(function(_, pane)
    if #pane:tab():panes() < 2 then return end
    local tab = pane:move_to_new_tab()
    tab:activate()
  end),
})

table.insert(config.keys, {
  key = 'w', mods = 'CTRL|ALT',
  action = wezterm.action_callback(function(_, pane)
    local _, window = pane:move_to_new_window()
    window:gui_window():focus()
  end),
})


-- Reading process info is costly, so cache it per pane for 3 seconds
local cache = {}

wezterm.on('format-tab-title', function(tab)
  local p = tab.active_pane
  local c = cache[p.pane_id]
  if not c or os.time() - c.at >= 3 then
    local mux_pane = wezterm.mux.get_pane(p.pane_id)
    local ok, argv = pcall(user_ssh_argv, mux_pane)
    c = {
      at = os.time(),
      target = ok and argv and ssh_target(argv),
    }
    cache[p.pane_id] = c
  end
  -- p.user_vars.ssh_target (set by the reconnect script) survives ssh exiting on disconnect,
  -- when there's no ssh process left for c.target's process-tree walk to find. Fall back titles
  -- are sometimes a full path (e.g. "C:\WINDOWS\...\powershell.exe"); show just the last path
  -- segment instead of the whole thing.
  local ssh_label = p.user_vars.ssh_target or c.target
  local label = ssh_label or (p.title:match('([^\\/]+)$') or p.title)
  local text = string.format(' %d: %s ', tab.tab_index + 1, label)
  if not ssh_label then return text end
  -- Colored circle emoji carry their own color (green/red) from the emoji font itself, unlike a
  -- Foreground attribute set via wezterm.format, which bleeds into later tab-title segments and
  -- even the close button and can't be reset reliably (wezterm/wezterm#7167). So a plain emoji
  -- glyph is the robust way to color part of a tab title without touching the rest of it.
  local dot = p.user_vars.ssh_disconnected == '1' and '\u{1F534}' or '\u{1F7E2}'
  return dot .. text
end)

return config
